[project]
name = "pytest-anki"
version = "2.0.0-dev.1"
description = "A pytest plugin for testing Anki add-ons"
authors = [
    { name = "Aristotelis P. (Glutanimate)" },
    { name = "Michal Krassowski" },
]
requires-python = "~=3.9"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["anki", "development", "testing", "test", "pytest"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: User Interfaces",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
]
# TODO: Make selenium optional
dependencies = [
    "pytest~=6.2.5",
    "pytest-qt~=4.4.0",
    "selenium>=3.141.0,<4",
    "packaging~=21.3",
    "aqt>=2.1.54",
    "anki>=2.1.54",
]

[project.urls]
Homepage = "https://github.com/glutanimate/pytest-anki"
Repository = "https://github.com/glutanimate/pytest-anki"

[project.entry-points.pytest11]
anki = "pytest_anki.plugin"

[project.optional-dependencies]
anki-2154 = ["aqt==2.1.54", "anki==2.1.54"]
anki-2165 = ["aqt==2.1.65", "anki==2.1.65"]
anki-2312 = ["aqt==23.12.1", "anki==23.12.1"]
anki-2411 = ["aqt==24.11", "anki==24.11"]

qt5-2154 = ["PyQt5~=5.15.5", "PyQt5-Qt5~=5.15.2", "PyQtWebEngine~=5.15.2"]
qt5-2165 = ["PyQt5~=5.15.5", "PyQt5-Qt5~=5.15.2", "PyQtWebEngine~=5.15.2"]
qt5-2312 = ["PyQt5~=5.15.5", "PyQt5-Qt5~=5.15.2", "PyQtWebEngine~=5.15.2"]
qt5-2411 = ["PyQt5~=5.15.5", "PyQt5-Qt5~=5.15.2", "PyQtWebEngine~=5.15.2"]

qt6-2154 = ["PyQt6~=6.3.1", "PyQt6-Qt6~=6.3.1", "PyQt6-WebEngine~=6.3.1"]
qt6-2165 = ["PyQt6~=6.5.0", "PyQt6-Qt6~=6.5.0", "PyQt6-WebEngine~=6.5.0"]
qt6-2312 = ["PyQt6~=6.6.1", "PyQt6-Qt6~=6.6.1", "PyQt6-WebEngine~=6.6.0"]
qt6-2411 = ["PyQt6~=6.6.1", "PyQt6-Qt6~=6.6.1", "PyQt6-WebEngine~=6.6.0"]

recommended-plugins = [
    "pytest-xvfb~=3.1.1",
    "pytest-xdist~=2.5.0",
    "pytest-forked~=1.4.0",
]

# TODO: Might need to add some of the recommended plugins to dev dependencies?
[dependency-groups]
dev = [
    "ruff~=0.11.0",
    "pylint~=3.3",
    "mypy~=1.15",
    "requests~=2.26",
    "types-requests~=2.25",
]
anki = ["aqt>=2.1.54", "anki>=2.1.54"]
qt5 = ["PyQt5>=5.15.2", "PyQt5-Qt5>=5.15.2", "PyQtWebEngine>=5.15.2", "PyQt5-stubs>=5.15.2"]
qt6 = ["PyQt6>=6.3.1", "PyQt6-Qt6>=6.3.1", "PyQt6-WebEngine>=6.3.1"]


[tool.uv]
default-groups = ["dev", "qt5", "qt6", "anki"]
conflicts = [
    [
        { extra = "anki-2154" },
        { extra = "anki-2165" },
        { extra = "anki-2312" },
        { extra = "anki-2411" },
    ],
    [
        { extra = "qt5-2154" },
        { extra = "qt5-2165" },
        { extra = "qt5-2312" },
        { extra = "qt5-2411" },
    ],
    [
        { extra = "qt6-2154" },
        { extra = "qt6-2165" },
        { extra = "qt6-2312" },
        { extra = "qt6-2411" },
    ],
]

[tool.hatch.build.targets.sdist]
include = ["pytest_anki/py.typed", "pytest_anki/anki-current.json"]

[tool.hatch.build.targets.wheel]
include = ["pytest_anki/py.typed", "pytest_anki/anki-current.json"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
qt_api = "pyqt5"

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
follow_imports = "silent"
show_column_numbers = true
exclude = "tests/samples/"

[tool.ruff]
line-length = 88
target-version = "py38"
extend-exclude = ["__pycache__", "tests/samples"]
ignore = ["E203", "E266", "E501"]
lint.select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["pytest_anki"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
combine-as-imports = true
split-on-trailing-comma = true
