name: tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/dependabot.yml"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/dependabot.yml"

jobs:
  test-anki-matrix:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - anki: anki-2154
            python: 3.9.15
            qt: qt6-2154
            chrome: 94.0.4606.126
          - anki: anki-2165
            python: 3.9.15
            qt: qt6-2165
            chrome: 108.0.5359.220
          - anki: anki-2312
            python: 3.9.15
            qt: qt6-2312
            chrome: 112.0.5615.213
          - anki: anki-2411
            python: 3.9.18
            qt: qt6-2411
            chrome: 112.0.5615.213

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
          chrome: ${{ matrix.chrome }}
          anki: ${{ matrix.anki }}
          qt: ${{ matrix.qt }}

      - name: Run tests for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make test
